### ISSUE TITLE
Couldn't register with accessibility bus:

### ISSUE THREAD

**Issue by eox-cs1** [perseo22/pacmanager#1]
Since today I'm getting this message, just before the actual ssh-login into machines. 

"WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken. at /usr/lib/perl5/Gtk2.pm line 138"

Since the login works after this message - it's obiously not a "broken network connection". 
I'm getting this on various (Debian, Ubuntu, Centos) machines.  I was running PAC 4.5.5.4 when I first encountered this message, so I upgraded to PAC 4.5.5.5, but no change. 

ciao

**Comment by perseo22** [comment]
Ok, it looks like _something_ changed in your system since today...

Those messages""WARNING **: Couldn't register with accessibility bus: Did not...bla bla bla..." are not generated by PAC, but come from Gtk, and, to be honest, I have no idea on  what do they mean at all!! :)

Anyway, as you say, they look (like many other Gtk messages) not to be harness at all, since at the very end, your connections are succeeding, aren't them?
- David.

**Comment by eox-cs1** [comment]
Dear David, 
Yes, the connections are succeeding at the end. But to be honest, error messages during a ssh-connection make me a little uneasy/tense. 
Especially since these errors do not show up when I ssh-connect from a plain GNOME Terminal. I therefore assume that there is some communication problem between PAC and the targets which does not work 100% correctly.  Maybe it really nothing serious and maybe its just some Gtk-version related problem.  But as said I don't like errors when using ssh.  I therefore wanted to let you know about this so you can check it. 

BTW, PAC is really a helpful tool. Thanks.

**Comment by perseo22** [comment]
Hi!
I really appreciate your information about these kind of messages, but unfortunately, I can't reproduce them... :(

Anyway, I'll stay tuned to see if that ever shows up in my desktop.

Thanks to you so for using PAC!! :+1: 
- David.
